require 'heroku/command/deploy'
require 'heroku/command/deploy/helpers'
require 'heroku/command/deploy/pack'
require 'heroku/command/deploy/pack/rails'
require 'heroku/command/deploy/pack/django'
require 'heroku/command/deploy/string_extensions'
